
---
- name: Remove cache files from root directory
  hosts: mymachines
  become: yes  # This is important to gain root privileges
  tasks:
    - name: Remove cache files in /root/.cache
      ansible.builtin.shell: 
        cmd: rm -rf /root/.cache/*