---
- name: Playbook to distribute keys
  hosts: mymachines
  become: true
  become_user: root
  
  tasks:
    - name: Copy ssh public keys to remote machines
      ansible.builtin.copy:
        src: /home/ec2-user/.ssh/project_identity.pub
        dest: /home/ec2-user/.ssh/project_identity.pub
        mode: '0644'

    - name: Add SSH key to authorized_keys
      ansible.builtin.authorized_key:
        user: ec2-user  
        state: present  # Ensures the key is present in the file.
        key: "{{ lookup('file', '/home/ec2-user/.ssh/project_identity.pub') }}"
