- name: On the device, get the data volume mounted and ready to use
  hosts: mymachines
  tasks:
    - name: Create a mount point for the data volume
      ansible.builtin.file:
        path: data/
        state: directory
        mode: '0755' 
    - name: Format the volume as ext3
      community.general.filesystem:
        dev: /dev/nvme1n1
        fstype: ext4
      become: true
    - name: Mount the filesystem
      ansible.posix.mount:
        name: data
        src: /dev/nvme1n1
        fstype: ext4
        state: mounted 
      become: true
    - name: Change the owner back to ec2-user after mounting
      become: true
      ansible.builtin.file:
        path: data/
        state: directory
        mode: 0755
        owner: ec2-user