- name: Node exporter installation
  hosts: mymachines
  become: true
  become_user: root
  tasks:
  - name: Accept repo GPG key
    ansible.builtin.shell:
      cmd: rpm --import https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9

  - name: Install EPEL
    ansible.builtin.dnf:
      name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
      state: present

  - name: Install node-exporter
    ansible.builtin.dnf:
      name: golang-github-prometheus-node-exporter
      state: latest

  - name: Move service file to where the service files live on the remote machines
    ansible.builtin.copy:
      src: ~/UCL_COMP0235_BIOCHEM_PROJECT/node_exporter.service
      dest: /etc/systemd/system/node_exporter.service 
      owner: root
      group: root

  - name: Start node-exporter
    ansible.builtin.service:
      name: node_exporter
      state: started
      daemon_reload: true

  - name: Open port 9100 for node exporter
    ansible.posix.firewalld:
      port: 9100/tcp
      permanent: true
      state: enabled
      zone: public
      immediate: true
      
  - name: Open port 4505 for custom metrics
    ansible.posix.firewalld:
      port: 4505/tcp
      permanent: true
      state: enabled
      zone: public
      immediate: true