---
- name: Install Python and necessary packages
  hosts: mymachines
  become: true
  tasks:
    - name: Install yum packages for Python and tools
      ansible.builtin.yum:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-pip
        - unzip
        - git
        - wget
      
    - name: Install Python dependencies with pip
      ansible.builtin.pip:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - numpy
          - scipy
          - biopython
          - pandas
          - prometheus_client

    - name: Install PyTorch (CPU version)
      ansible.builtin.pip:
        name: torch
        extra_args: "--index-url https://download.pytorch.org/whl/cpu"
        state: forcereinstall

    - name: Install firewalld
      ansible.builtin.dnf:
        name: firewalld
        state: present

    - name: Enable firewalld service
      ansible.builtin.systemd:
        name: firewalld
        enabled: yes

    - name: Start firewalld service
      ansible.builtin.systemd:
        name: firewalld
        state: started

    - name: Open HTTP service in the firewall
      ansible.posix.firewalld:
        service: http
        permanent: yes
        state: enabled
        immediate: yes
        zone: public

    - name: Reload firewalld
      ansible.builtin.command:
        cmd: firewall-cmd --reload

          